/**
 * CineOrder — Catalog Completeness Store
 *
 * Manages proposals generated by the Catalog Completeness Audit Engine.
 * Supports review workflows, approval gates, filters, and persistence.
 */

import { CatalogCompletenessAuditEngine } from './catalogCompletenessAuditEngine';
import type {
  CandidateMissingTitleProposal,
  GlobalCompletenessAuditReport,
  CompletenessGapType,
  ProposalReviewStatus,
} from '@/types/catalogCompletenessAudit';

const STORAGE_KEY = 'cineorder_catalog_completeness_proposals_v1';

export class CatalogCompletenessStore {
  private static instance: CatalogCompletenessStore;
  private proposals: CandidateMissingTitleProposal[] = [];
  private lastReport: GlobalCompletenessAuditReport | null = null;

  private constructor() {
    this.loadState();
  }

  public static getInstance(): CatalogCompletenessStore {
    if (!CatalogCompletenessStore.instance) {
      CatalogCompletenessStore.instance = new CatalogCompletenessStore();
    }
    return CatalogCompletenessStore.instance;
  }

  private loadState(): void {
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        const raw = window.localStorage.getItem(STORAGE_KEY);
        if (raw) {
          const parsed = JSON.parse(raw);
          if (Array.isArray(parsed)) {
            this.proposals = parsed;
            return;
          }
        }
      }
    } catch {
      // Corrupted storage recovery: reset gracefully
      this.proposals = [];
    }

    // Default: run initial scan
    const report = CatalogCompletenessAuditEngine.runGlobalAudit();
    this.lastReport = report;
    this.proposals = report.allProposals;
    this.saveState();
  }

  private saveState(): void {
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        window.localStorage.setItem(STORAGE_KEY, JSON.stringify(this.proposals));
      }
    } catch {
      // Storage unavailable or disabled
    }
  }

  public getProposals(): CandidateMissingTitleProposal[] {
    return [...this.proposals];
  }

  public getReport(forceRefresh = false): GlobalCompletenessAuditReport {
    if (!this.lastReport || forceRefresh) {
      this.lastReport = CatalogCompletenessAuditEngine.runGlobalAudit();
      // Synchronize existing review statuses
      const statusMap = new Map(this.proposals.map((p) => [p.proposalId, p.reviewStatus]));
      for (const proposal of this.lastReport.allProposals) {
        if (statusMap.has(proposal.proposalId)) {
          proposal.reviewStatus = statusMap.get(proposal.proposalId)!;
        }
      }
      this.proposals = this.lastReport.allProposals;
      this.saveState();
    }
    return this.lastReport;
  }

  public updateProposalStatus(
    proposalId: string,
    status: ProposalReviewStatus,
    reviewer = 'Editorial Lead',
    notes?: string
  ): boolean {
    const found = this.proposals.find((p) => p.proposalId === proposalId);
    if (!found) return false;

    found.reviewStatus = status;
    found.reviewedBy = reviewer;
    found.reviewedAt = new Date().toISOString();
    found.reviewNotes = notes;
    found.updatedAt = new Date().toISOString();

    this.saveState();
    return true;
  }

  public filterProposals(params: {
    status?: ProposalReviewStatus | 'all';
    gapType?: CompletenessGapType | 'all';
    franchiseId?: string;
    searchQuery?: string;
  }): CandidateMissingTitleProposal[] {
    const { status = 'all', gapType = 'all', franchiseId, searchQuery } = params;

    return this.proposals.filter((p) => {
      if (status !== 'all' && p.reviewStatus !== status) return false;
      if (gapType !== 'all' && p.gapType !== gapType) return false;
      if (franchiseId && franchiseId !== 'all' && p.franchiseId !== franchiseId) return false;
      if (searchQuery) {
        const q = searchQuery.toLowerCase().trim();
        const matchesTitle = p.title.toLowerCase().includes(q);
        const matchesFranchise = p.franchiseName.toLowerCase().includes(q);
        const matchesContinuity = p.continuity.toLowerCase().includes(q);
        if (!matchesTitle && !matchesFranchise && !matchesContinuity) return false;
      }
      return true;
    });
  }

  public resetToDefault(): void {
    const report = CatalogCompletenessAuditEngine.runGlobalAudit();
    this.lastReport = report;
    this.proposals = report.allProposals;
    this.saveState();
  }
}

export const catalogCompletenessStore = CatalogCompletenessStore.getInstance();
