import { generatePreparationGuide } from '@/lib/preparationGuide';
import { formatRuntime } from '@/lib/utils';
import type { DailyScheduleItem, PersonalWatchPlan } from '@/types/planner';

/**
 * Generates an automatic daily watch schedule for a target movie or TV series
 * based on user's daily hour availability and preferred watching days.
 */
export function generatePersonalSchedule(
  targetContentId: string,
  hoursPerDay: number = 2,
  _daysPerWeek: number = 4,
  preferredDays: string[] = ['Mon', 'Wed', 'Fri', 'Sat'],
  userWatchedIds: string[] = []
): DailyScheduleItem[] {
  const guide = generatePreparationGuide(targetContentId, userWatchedIds);
  if (!guide) return [];

  // Combine Must Watch and Recommended unwatched items
  const prerequisites = [...guide.mustWatch, ...guide.recommended].filter(
    (r) => !r.isWatched
  );

  if (prerequisites.length === 0) return [];

  const maxDailyMinutes = hoursPerDay * 60;
  const schedule: DailyScheduleItem[] = [];

  let dayCounter = 1;
  const currentDate = new Date();
  currentDate.setDate(currentDate.getDate() + 1); // Start tomorrow

  const dayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

  for (const item of prerequisites) {
    const c = item.content;
    const isSeries = c.type === 'series';

    if (isSeries) {
      const totalEp = 6;
      const epPerBatch = Math.max(2, Math.floor(maxDailyMinutes / 45));
      const batches = Math.ceil(totalEp / epPerBatch);

      for (let b = 0; b < batches; b++) {
        const startEp = b * epPerBatch + 1;
        const endEp = Math.min(totalEp, (b + 1) * epPerBatch);
        const batchDuration = (endEp - startEp + 1) * 45;

        while (!preferredDays.includes(dayNames[currentDate.getDay()] || 'Mon')) {
          currentDate.setDate(currentDate.getDate() + 1);
        }

        const dateStr = currentDate.toISOString().split('T')[0] || '2026-08-01';

        schedule.push({
          id: `sched-${c.id}-ep${startEp}-${endEp}-${dayCounter}`,
          dayNumber: dayCounter,
          dateString: dateStr,
          contentId: c.id,
          title: c.title,
          type: 'episode_chunk',
          detailText: `${c.title} Episodes ${startEp}-${endEp} (${formatRuntime(batchDuration)})`,
          durationMinutes: batchDuration,
          isCompleted: false,
        });

        dayCounter++;
        currentDate.setDate(currentDate.getDate() + 1);
      }
    } else {
      while (!preferredDays.includes(dayNames[currentDate.getDay()] || 'Mon')) {
        currentDate.setDate(currentDate.getDate() + 1);
      }

      const dateStr = currentDate.toISOString().split('T')[0] || '2026-08-01';

      schedule.push({
        id: `sched-${c.id}-${dayCounter}`,
        dayNumber: dayCounter,
        dateString: dateStr,
        contentId: c.id,
        title: c.title,
        type: 'movie',
        detailText: `${c.title} (${formatRuntime(c.runtime || 120)})`,
        durationMinutes: c.runtime || 120,
        isCompleted: false,
      });

      dayCounter++;
      currentDate.setDate(currentDate.getDate() + 1);
    }
  }

  return schedule;
}

/**
 * Export Watch Plan to CSV
 */
export function exportPlanCSV(plan: PersonalWatchPlan): string {
  const headers = ['Day', 'Date', 'Title', 'Type', 'Schedule Detail', 'Duration (min)', 'Status'];
  const rows = plan.schedule.map((item) => [
    `Day ${item.dayNumber}`,
    item.dateString,
    `"${item.title.replace(/"/g, '""')}"`,
    item.type,
    `"${item.detailText.replace(/"/g, '""')}"`,
    item.durationMinutes,
    item.isCompleted ? 'Completed' : 'Pending',
  ]);

  return [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
}

/**
 * Export Watch Plan to Printable Text Checklist
 */
export function exportPlanText(plan: PersonalWatchPlan): string {
  const lines: string[] = [
    `==================================================`,
    `CINEORDER PERSONAL WATCH PLAN: ${plan.targetTitle.toUpperCase()}`,
    `Target Release Date: ${plan.targetReleaseDate}`,
    `Daily Time Commitment: ${plan.hoursPerDay} hours/day`,
    `==================================================\n`,
  ];

  plan.schedule.forEach((item) => {
    const check = item.isCompleted ? '[X]' : '[ ]';
    lines.push(`${check} Day ${item.dayNumber} (${item.dateString}): ${item.detailText}`);
  });

  lines.push(`\nGenerated by CineOrder AI Preparation Engine.`);
  return lines.join('\n');
}
