import type { CKGEdgeRelationship } from '@/data/cineOrderKnowledgeGraph';
import type { CategoryType } from '@/types/preparation';

export interface RelationshipDefinition {
  id: CKGEdgeRelationship;
  label: string;
  description: string;
  drivesMainPlot: boolean;
  drivesCharacterArc: boolean;
  drivesWorldState: boolean;
  spoilerRisk: 'none' | 'low' | 'medium' | 'high';
  defaultModerateCategory: CategoryType;
}

export const RELATIONSHIP_REGISTRY: Record<CKGEdgeRelationship, RelationshipDefinition> = {
  'direct-sequel': {
    id: 'direct-sequel',
    label: 'Direct Sequel',
    description: 'Direct narrative continuation following immediate story events.',
    drivesMainPlot: true,
    drivesCharacterArc: true,
    drivesWorldState: true,
    spoilerRisk: 'high',
    defaultModerateCategory: 'recommended',
  },
  'story-continuation': {
    id: 'story-continuation',
    label: 'Story Continuation',
    description: 'Carries active plot threads forward across titles.',
    drivesMainPlot: true,
    drivesCharacterArc: true,
    drivesWorldState: false,
    spoilerRisk: 'medium',
    defaultModerateCategory: 'recommended',
  },
  'character-origin': {
    id: 'character-origin',
    label: 'Character Origin',
    description: 'Establishes foundational backstory and introduction for a major character.',
    drivesMainPlot: false,
    drivesCharacterArc: true,
    drivesWorldState: false,
    spoilerRisk: 'low',
    defaultModerateCategory: 'optional',
  },
  'character-development': {
    id: 'character-development',
    label: 'Character Development',
    description: 'Expands emotional growth, relationships, or traumatic history of a key protagonist.',
    drivesMainPlot: false,
    drivesCharacterArc: true,
    drivesWorldState: false,
    spoilerRisk: 'low',
    defaultModerateCategory: 'optional',
  },
  mentor: {
    id: 'mentor',
    label: 'Mentor Dynamic',
    description: 'Establishes a mentorship or guiding relationship between key figures.',
    drivesMainPlot: false,
    drivesCharacterArc: true,
    drivesWorldState: false,
    spoilerRisk: 'low',
    defaultModerateCategory: 'optional',
  },
  'villain-origin': {
    id: 'villain-origin',
    label: 'Villain Origin',
    description: 'Details the origin or motivations of an antagonist.',
    drivesMainPlot: true,
    drivesCharacterArc: false,
    drivesWorldState: false,
    spoilerRisk: 'medium',
    defaultModerateCategory: 'optional',
  },
  'shared-villain': {
    id: 'shared-villain',
    label: 'Shared Antagonist',
    description: 'Features a recurring antagonist connecting separate storylines.',
    drivesMainPlot: false,
    drivesCharacterArc: false,
    drivesWorldState: false,
    spoilerRisk: 'low',
    defaultModerateCategory: 'optional',
  },
  'shared-character': {
    id: 'shared-character',
    label: 'Shared Character',
    description: 'Includes supporting character crossover.',
    drivesMainPlot: false,
    drivesCharacterArc: false,
    drivesWorldState: false,
    spoilerRisk: 'none',
    defaultModerateCategory: 'optional',
  },
  'shared-event': {
    id: 'shared-event',
    label: 'Shared Catalyst Event',
    description: 'Shares an overarching historical or major crossover event.',
    drivesMainPlot: false,
    drivesCharacterArc: false,
    drivesWorldState: true,
    spoilerRisk: 'medium',
    defaultModerateCategory: 'optional',
  },
  'shared-object': {
    id: 'shared-object',
    label: 'Shared MacGuffin / Object',
    description: 'Tracks an artifact or object passing between titles.',
    drivesMainPlot: true,
    drivesCharacterArc: false,
    drivesWorldState: false,
    spoilerRisk: 'low',
    defaultModerateCategory: 'optional',
  },
  organization: {
    id: 'organization',
    label: 'Organization Context',
    description: 'Establishes faction, agency, or group context.',
    drivesMainPlot: false,
    drivesCharacterArc: false,
    drivesWorldState: true,
    spoilerRisk: 'none',
    defaultModerateCategory: 'optional',
  },
  timeline: {
    id: 'timeline',
    label: 'Timeline Mechanics',
    description: 'Involves time manipulation, altered timelines, or temporal rules.',
    drivesMainPlot: true,
    drivesCharacterArc: false,
    drivesWorldState: true,
    spoilerRisk: 'high',
    defaultModerateCategory: 'optional',
  },
  multiverse: {
    id: 'multiverse',
    label: 'Multiverse Connection',
    description: 'Connects alternate realities, variants, or dimensional incursions.',
    drivesMainPlot: true,
    drivesCharacterArc: false,
    drivesWorldState: true,
    spoilerRisk: 'high',
    defaultModerateCategory: 'optional',
  },
  'world-building': {
    id: 'world-building',
    label: 'World Building',
    description: 'Expands shared universe lore, geography, or historical rules.',
    drivesMainPlot: false,
    drivesCharacterArc: false,
    drivesWorldState: true,
    spoilerRisk: 'none',
    defaultModerateCategory: 'optional',
  },
  'post-credit': {
    id: 'post-credit',
    label: 'Post-Credit Scene',
    description: 'Teases future storylines or post-credit cameos.',
    drivesMainPlot: false,
    drivesCharacterArc: false,
    drivesWorldState: false,
    spoilerRisk: 'low',
    defaultModerateCategory: 'post_credit',
  },
  'major-crossover': {
    id: 'major-crossover',
    label: 'Major Crossover Event',
    description: 'Large-scale team assembly or multi-franchise crossover.',
    drivesMainPlot: true,
    drivesCharacterArc: true,
    drivesWorldState: true,
    spoilerRisk: 'high',
    defaultModerateCategory: 'optional',
  },
  'thematic-callback': {
    id: 'thematic-callback',
    label: 'Thematic Callback',
    description: 'Parallels or echoes themes, dialogue, or symbolism from prior entries.',
    drivesMainPlot: false,
    drivesCharacterArc: false,
    drivesWorldState: false,
    spoilerRisk: 'none',
    defaultModerateCategory: 'optional',
  },
  'same-universe-only': {
    id: 'same-universe-only',
    label: 'Same Universe Background',
    description: 'Minimal connection beyond sharing the same fictional universe.',
    drivesMainPlot: false,
    drivesCharacterArc: false,
    drivesWorldState: false,
    spoilerRisk: 'none',
    defaultModerateCategory: 'optional',
  },
};
